if(NOT DEFINED VCPKG_TARGET_TRIPLET)
  set(VCPKG_TARGET_TRIPLET "aarch64-linux-gnu" CACHE STRING "")
endif()

# Set system.
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_CROSSCOMPILING ON CACHE BOOL "")
set(CMAKE_SYSTEM_PROCESSOR aarch64 CACHE STRING "")
set(CMAKE_SYSTEM_NAME Linux CACHE STRING "")

# Set compiler.
set(CMAKE_C_COMPILER "aarch64-unknown-linux-gnu-gcc" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "aarch64-unknown-linux-gnu-g++" CACHE STRING "" FORCE)
set(CMAKE_RANLIB "aarch64-unknown-linux-gnu-ranlib" CACHE STRING "" FORCE)
set(CMAKE_AR "aarch64-unknown-linux-gnu-ar" CACHE STRING "" FORCE)
set(CMAKE_NM "aarch64-unknown-linux-gnu-nm" CACHE STRING "" FORCE)
set(CMAKE_LD "aarch64-unknown-linux-gnu-ld" CACHE STRING "" FORCE)

# Base Flags
set(BASE_FLAGS "-Wall -Wextra -Wpedantic -Wno-unused-parameter -Wno-unused-variable -mtune=cortex-a53 -march=armv8-a -flto")

# Compiler Flags
set(CMAKE_C_FLAGS "-fasm -fPIC ${BASE_FLAGS} ${VCPKG_C_FLAGS} -pthread" CACHE STRING "")
set(CMAKE_C_FLAGS_DEBUG "-O0 -g ${VCPKG_C_FLAGS_DEBUG}" CACHE STRING "")
set(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG ${VCPKG_C_FLAGS_RELEASE}" CACHE STRING "")
set(CMAKE_C_FLAGS_MINSIZEREL "-Os -DNDEBUG ${VCPKG_C_FLAGS_RELEASE}" CACHE STRING "")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG ${VCPKG_C_FLAGS_RELEASE}" CACHE STRING "")

set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} ${VCPKG_CXX_FLAGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} ${VCPKG_CXX_FLAGS_DEBUG}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} ${VCPKG_CXX_FLAGS_RELEASE}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL} ${VCPKG_CXX_FLAGS_RELEASE}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} ${VCPKG_CXX_FLAGS_RELEASE}" CACHE STRING "")

# Linker Flags
foreach(LINKER SHARED_LINKER MODULE_LINKER EXE_LINKER)
  set(CMAKE_${LINKER}_FLAGS "${VCPKG_LINKER_FLAGS}" CACHE STRING "")
  set(CMAKE_${LINKER}_FLAGS_DEBUG "${VCPKG_LINKER_FLAGS_DEBUG}" CACHE STRING "")
  set(CMAKE_${LINKER}_FLAGS_RELEASE "${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
  set(CMAKE_${LINKER}_FLAGS_MINSIZEREL "${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
  set(CMAKE_${LINKER}_FLAGS_RELWITHDEBINFO "${LLVM_STATIC_LIBCXX} ${VCPKG_LINKER_FLAGS_RELEASE}" CACHE STRING "")
endforeach()

